Navbar netjes ingesprongen. Weekend!
DamianR2004/pleasurable-ui pull request #4
Opened 2024-05-15 09:27 UTC by DamianR2004

Check 'm ff Lemuel :)

2024-05-15 09:29 UTC, lemuelmgsn requested changes
mag wel wat beter! inspringen graag met 2 tabs.

2024-05-15 09:30 UTC, DamianR2004 commented
wordt opgelost

2024-05-22 10:33 UTC, lemuelmgsn approved these changes
Goed gedaan, mooie responsive navbar gemaakt!

2024-05-22 10:50 UTC, merged

2024-05-24 08:39 UTC, DamianR2004 commented
What does this change?
Resolves issue #1 

[livesite](https://pleasurable-ui-so87.onrender.com)

Ontwerp in Figma:

https://www.figma.com/design/38S2dQECTMDioJicXKNdnY/Untitled?node-id=0-1&t=4lmIavW9zPStPMh8-0

2024-05-24 08:46 UTC, IvarSchuyt commented on views/partials/housebutton.ejs
> +<svg fill="#ffffff" height="64px" width="64px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 486.196 486.196" xml:space="preserv
Je kan svgomg gebruiken om grote svg's kleiner te maken

2024-05-24 08:48 UTC, kosterm14 commented
Ik zou de pull request een wat uitbreidere message geven. [Hier](https://github.com/fdnd-agency/.github/blob/main/pull_request_template.md) heb je de pull request template die wij in het tweede jaar gebruiken

<img src= "https://github.com/DamianR2004/pleasurable-ui/assets/61830362/042e52b1-740d-47af-bfc6-060bdfcf3cdd" width= 40%>

Bij images kun je goed een before en een after image toevoegen om goed te laten zien wat je veranderd met deze pull request

Ook zou ik een soort van "how to review" kopje toevoegen om duidelijk te maken hoe de reviewer bij de wijziging komt op je website. Hieronder heb ik een voorbeeld van mijn pull request zodat je ziet hoe ik dat doe.

![image](https://github.com/DamianR2004/pleasurable-ui/assets/61830362/c19f425b-a2bb-4162-9e4d-ebff400c4df8)